name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Ruby
        uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
        with:
          ruby-version: 2.7
      - name: build
        run: |
          bundle install
          npm install
          npm run build
      - name: publish
        # Derived from helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        run: |
          cd _site
          
          remote_branch=gh-pages
          if [ "${GITHUB_REF}" = "refs/heads/${remote_branch}" ]; then
            echo "::error::Cannot publish on branch ${remote_branch}"
            exit 1
          fi

          echo "Publishing to ${GITHUB_REPOSITORY} on branch ${remote_branch}"
          echo "::debug::Pushing to https://${JEKYLL_PAT}@github.com/${GITHUB_REPOSITORY}.git"

          remote_repo="https://${JEKYLL_PAT}@github.com/${GITHUB_REPOSITORY}.git" && \
          git init && \
          git config user.name "${GITHUB_ACTOR}" && \
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          git add . && \
          git commit -m "jekyll build from Action ${GITHUB_SHA}" && \
          git push --force $remote_repo master:$remote_branch
